os: RHEL
dist: rhel8
language: python
arch: amd64
python:
    - "3.9-dev"  # 3.9 development branch
    - "nightly"  # nightly build
before_install:
    - yum install -y rpm
script:
    - python hello_world.py
